- hosts: ldapuser
  remote_user: root
  tasks:
  - name: close firewalld
    service: name=firewalld state=stopped
  - name: close iptables
    shell: iptables -F
  - name: install ldap.pkg
    yum: name=openldap state=present
  - name: install ldap.pkg
    yum: name=openldap-clients state=present
  - name: install ldap.pkg
    yum: name=nss-pam-ldapd state=present
  - name: ldap.host
    shell: echo "192.168.78.50 server-50" >> /etc/hosts
  - name: ldap anthconfig
    shell: authconfig --enableldap --enableldapauth --ldapserver=server-50 --ldapbasedn="dc=example,dc=org" --enableldaptls --ldaploadcacert=http://server-50/ca.crt   --update
  - name: install autofs
    yum: name=autofs state=present
  - name: creat autofs
    shell: echo "/ldapuser /etc/auto.ldap" >> /etc/auto.master
  - name: creat autofs
    shell: echo '* -rw,sync 192.168.78.50:/ldapuser/&' > /etc/auto.ldap
  - name: start autofs
    service: name=autofs state=started
    notify:
    - start autofs

  handlers:
  - name: start autofs
    service: name=autofs state=restarted
